default_language_version:
    python: python3

default_stages: [commit, push]

ci:
    autofix_commit_msg: |
        [pre-commit.ci] auto fixes from pre-commit.com hooks

        for more information, see https://pre-commit.ci
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: 'quarterly'
    skip: []
    submodules: false

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
        - id: check-toml
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: mixed-line-ending
        - id: detect-private-key
        - id: name-tests-test
          args: [--pytest-test-first]
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
          - id: black
    - repo: https://github.com/PyCQA/flake8.git
      rev: 16c371d41cd742f975171826de0ad5d707162c1d
      hooks:
          - id: flake8
    - repo: https://github.com/hadialqattan/pycln
      rev: v2.1.3
      hooks:
          - id: pycln
            args: [--config=pyproject.toml]
    - repo: https://github.com/pycqa/isort
      rev: 5.11.5
      hooks:
          - id: isort
            files: "\\.(py)$"
            args: ["--profile", "black"]
    - repo: https://github.com/tox-dev/pyproject-fmt
      rev: 0.9.0
      hooks:
        - id: pyproject-fmt
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
        - id: python-check-blanket-noqa
        - id: python-check-mock-methods
        - id: python-no-eval
        - id: python-no-log-warn
        - id: rst-backticks
        - id: rst-directive-colons
